### ISSUE TITLE
game options are not saved

### ISSUE THREAD

**Issue by ddombrowsky** [ComputerScienceHouse/bingehack4#53]
Am I missing a magic button somewhere?  The following happens on games-ng.csh.rit.edu:
1. Change the "graphics" option to "plain"
2. quit
3. telnet back to the server

The graphics mode is now set back to unicode.  Same happens with any other options I set (name, sortpack, UI changes, etc.).

**Comment by liam-middlebrook** [comment]
Just tested on the current setup, this no longer appears to be an issue. Please re-open if you encounter this again!
