### ISSUE TITLE
Game Crash when taking off amulet

### ISSUE THREAD

**Issue by sdemos** [ComputerScienceHouse/bingehack4#73]
I was playing this morning and the game dropped me into a crash loop when I tried to take off an amulet. The amulet wasn't identified. The save file is still on the server if you want to check it out, I can't get to it since I'm not an RTP. Should be the older one. As soon as you open it it will try and load the save file and then crash saying `Server Programming error. Sorry about that!` or something like that and then try and load the game again, then fail, etc.

@dgonyeo @liam-middlebrook

**Comment by liam-middlebrook** [comment]
Fixed in: https://github.com/ComputerScienceHouse/bingehack4/commit/85dbdba39459cb83fc0010010daed47a86718c2b
